services:

  account-db:
    image: postgres:17
    container_name: account-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account_db

    ports:
      - "5432:5432"

    volumes:
      - account-db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d account_db"]
      interval: 5s
      timeout: 5s
      retries: 5


  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq


  account-service:
    build:
      context: ./account_Services
      dockerfile: Dockerfile

    container_name: account-service

    ports:
      - "3001:3001"

    environment:
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres@account-db:5432/account_db
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672

    depends_on:
      account-db:
        condition: service_healthy

      rabbitmq:
        condition: service_started


volumes:
  account-db-data:
  rabbitmq-data: